D("infra.opensuse.org", REG_OPENSUSE,

    DefaultTTL (3600),

    IGNORE     ("", "SSHFP"), // managed by /usr/local/sbin/salt2sshfp.py on chip.i.o.o

    A          ("acme",                 "172.16.164.103"                                                  ),
    A          ("atlas1",               "172.16.130.11"                                                   ),
    A          ("atlas2",               "172.16.130.12"                                                   ),
    AAAA       ("avalon1",              "fd03:7bbf:d626:1700::1"                                          ),
    AAAA       ("avalon2",              "fd03:7bbf:d626:1700::2"                                          ),
    A          ("chip",                 "172.16.164.30"                                                   ),
    A          ("dale",                 "172.16.164.138"                                                  ),
    A          ("discourse01",          "172.16.164.160"                                                  ),
    A          ("legacy-ip.discourse01","172.16.164.160"                                                  ),
    A          ("elections2",           "172.16.164.154"                                                  ),
    A          ("etherpad",             "172.16.164.140"                                                  ),
    A          ("hel",                  "172.16.164.6"                                                    ),
    A          ("legacy-ip.hel",        "172.16.164.6"                                                    ),
    A          ("hel1",                 "172.16.164.13"                                                   ),
    A          ("hel2",                 "172.16.164.14"                                                   ),
    A          ("ipx-narwal1",          "192.168.87.6"                                                    ),
    A          ("ipx-proxy1",           "192.168.87.5"                                                    ),
    A          ("ipx-rsync1",           "192.168.87.2"                                                    ),
    A          ("ipx-status1",          "192.168.87.3"                                                    ),
    A          ("ipx-stonehat",         "192.168.87.1"                                                    ),
    A          ("logger-prg",           "172.16.164.41"                                                   ),
    A          ("mailman3",             "172.16.164.159"                                                  ),
    A          ("mirrordb1",            "172.16.164.151"                                                  ),
    A          ("mirrordb2",            "172.16.164.152"                                                  ),
    A          ("monitor",              "172.16.164.40"                                                   ),
    A          ("mx-test",              "172.16.131.98"                                                   ),
    A          ("mx1",                  "172.16.131.11"                                                   ),
    A          ("mx2",                  "172.16.131.12"                                                   ),
    A          ("mybackup",             "172.16.164.146"                                                  ),
    A          ("narwal5",              "172.16.164.115"                                                  ),
    A          ("narwal6",              "172.16.164.116"                                                  ),
    A          ("narwal7",              "172.16.164.117"                                                  ),
    A          ("narwal8",              "172.16.164.102"                                                  ),
    A          ("obsreview",            "172.16.164.163"                                                  ),
    A          ("odin",                 "172.16.164.50"                                                   ),
    A          ("prg-ns1",              "172.16.130.21"                                                   ),
    A          ("prg-ns2",              "172.16.130.22"                                                   ),
    AAAA       ("proxy-prg2",           "2a07:de40:b27e:1204::10",                              TTL(1800) ),
    A          ("proxy-prg2",           "172.16.164.5",                                         TTL(1800) ),
    A          ("slc-ns1",              "172.16.113.6"                                                    ),
    A          ("slc-ns2",              "172.16.113.7"                                                    ),
    A          ("status3",              "172.16.164.167"                                                  ),
    A          ("thor",                 "172.16.164.11"                                                   ),
    A          ("thor1",                "172.16.164.11"                                                   ),
    A          ("witch1",               "172.16.164.101"                                                  ),

    CNAME      ("*.gitlab-pages",       "gitlab-pages.infra.opensuse.org."                                ),
    CNAME      ("alertmanager",         "monitor.infra.opensuse.org."                                     ),
    CNAME      ("alerts",               "monitor.infra.opensuse.org."                                     ),
    CNAME      ("dbproxy",              "proxy.infra.opensuse.org."                                       ),
    CNAME      ("download-nue",         "ipx-rsync1.infra.opensuse.org."                                  ),
    CNAME      ("download-prg",         "download.infra.opensuse.org."                                    ),
    CNAME      ("download-slc",         "slc-mirror.infra.opensuse.org."                                  ),
    CNAME      ("downloadtmp",          "download.infra.opensuse.org."                                    ),
    CNAME      ("elasticsearch",        "water.infra.opensuse.org."                                       ),
    CNAME      ("elections",            "elections2.infra.opensuse.org."                                  ),
    CNAME      ("events",               "dale.infra.opensuse.org."                                        ),
    CNAME      ("ext-ns",               "chip.infra.opensuse.org."                                        ),
    CNAME      ("galera",               "galera1.infra.opensuse.org."                                     ),
    CNAME      ("galera-backup",        "mybackup.infra.opensuse.org."                                    ),
    CNAME      ("gateway",              "gate.infra.opensuse.org."                                        ),
    CNAME      ("gcc",                  "gcc-stats.infra.opensuse.org."                                   ),
    CNAME      ("gitlab",               "mickey.infra.opensuse.org."                                      ),
    CNAME      ("gitlab-pages",         "gitlab.infra.opensuse.org."                                      ),
    CNAME      ("hackweek",             "dale.infra.opensuse.org."                                        ),
    CNAME      ("idm",                  "hel.infra.opensuse.org."                                         ),
    CNAME      ("idm-ext-dev",          "hel.infra.opensuse.org."                                         ),
    CNAME      ("ipx-proxy",            "ipx-proxy1.infra.opensuse.org."                                  ),
    CNAME      ("karma",                "monitor.infra.opensuse.org."                                     ),
    CNAME      ("ldap",                 "idm.infra.opensuse.org."                                         ),
    CNAME      ("legacy-ip.mysql",      "legacy-ip.hel.infra.opensuse.org."                               ),
    CNAME      ("logger",               "logger-prg.infra.opensuse.org."                                  ),
    CNAME      ("mirrordb",             "mirrordb2.infra.opensuse.org."                                   ),
    CNAME      ("mysql",                "hel.infra.opensuse.org."                                         ),
    CNAME      ("narwal1",              "ipx-narwal1.infra.opensuse.org."                                 ),
    CNAME      ("netbox",               "hel.infra.opensuse.org."                                         ),
    CNAME      ("ns1",                  "hel1.infra.opensuse.org."                                        ),
    CNAME      ("ns2",                  "hel2.infra.opensuse.org."                                        ),
    CNAME      ("ns3",                  "chip.infra.opensuse.org."                                        ),
    CNAME      ("ntp1",                 "hel1.infra.opensuse.org."                                        ),
    CNAME      ("ntp2",                 "hel2.infra.opensuse.org."                                        ),
    CNAME      ("ntp3",                 "tyr1.infra.opensuse.org."                                        ),
    CNAME      ("ntp4",                 "tyr2.infra.opensuse.org."                                        ),
    CNAME      ("osem",                 "dale.infra.opensuse.org."                                        ),
    CNAME      ("postgresql",           "hel.infra.opensuse.org."                                         ),
    CNAME      ("prometheus",           "monitor.infra.opensuse.org."                                     ),
    CNAME      ("provo-mirror",         "slc-mirror.infra.opensuse.org."                                  ),
    CNAME      ("qsc-ns3",              "ipx-ns1.infra.opensuse.org."                                     ),
    CNAME      ("relay",                "hel.infra.opensuse.org."                                         ),
    CNAME      ("rsync",                "ipx-rsync1.infra.opensuse.org."                                  ),
    CNAME      ("salt",                 "witch1.infra.opensuse.org."                                      ),
    CNAME      ("stage3",               "stage3.opensuse.org."                                            ),
    CNAME      ("status1",              "ipx-status1.infra.opensuse.org."                                 ),
    CNAME      ("stonehat",             "ipx-stonehat.infra.opensuse.org."                                ),
    CNAME      ("wiki",                 "riesling.infra.opensuse.org."                                    ),

    MX         ("@",                    42, "hel.infra.opensuse.org."                                     ),
);

// Generate AAAA and PTR records for hosts with definitions in pillar/infra/hosts.yaml
HOSTS("infra.opensuse.org", HOSTS_OPENSUSE);

// Generate AAAA and PTR records for hosts without such definitions
AAAA_AND_PTR_BULK("infra.opensuse.org", {
    "apollo":               "2a07:de40:b27e:1207::a",
    "arches20":             "2a07:de40:617e:1800::a0",
    "arches21":             "2a07:de40:617e:1800::a1",
    "arches22":             "2a07:de40:617e:1800::a2",
    "asgard1":              "2a07:de40:b27e:1203::1",
    "asgard2":              "2a07:de40:b27e:1203::2",
    "atlas":                "2a07:de40:b27e:1204::10",
    "atlas-login":          "2a07:de40:b27e:1204::7",
    "atlas-login1":         "2a07:de40:b27e:1204::8",
    "atlas-login2":         "2a07:de40:b27e:1204::9",
    "chaplin20":            "2a07:de40:617e:1800::20",
    "chaplin21":            "2a07:de40:617e:1800::21",
    "falkor20":             "2a07:de40:b27e:1201::f0",
    "falkor21":             "2a07:de40:b27e:1201::f1",
    "falkor22":             "2a07:de40:b27e:1201::f2",
    "gw-thor":              "2a07:de40:b27e:1100::3",
    "gw-thor1":             "2a07:de40:b27e:1100::1",
    "gw-thor2":             "2a07:de40:b27e:1100::2",
    "hel":                  "2a07:de40:b27e:1203::10",
    "ipx-ns1":              "2a07:de40:b27e:5002:c707:5ca1:19e:ce5e",
    "kepler20":             "2a07:de40:617e:1800::10",
    "kepler21":             "2a07:de40:617e:1800::11",
    "orbit20":              "2a07:de40:b27e:1201::a0",
    "orbit21":              "2a07:de40:b27e:1201::a1",
    "slimhat":              "2a07:de40:b27e:5001:4b26:fce8:5810:cf57",
    "squanchy":             "2a07:de40:b27e:1201::c",
    "thor":                 "2a07:de40:b27e:1100::a",
    "tyr":                  "2a07:de40:617e:1903::10",
});
