CNAME_BULK("opensuse.org", {
  "code": {
      "1h": [ 
          "ev",
          "pages",
          "releases",
      ],
  },
  "download": {
      "5m": [
          "codecs",
      ],
      "10m": [
          "download-repositories",
      ],
      "1h": [
          "mirrorcache",
          "mirrorcache-eu",
          "tracker",
          "tumbleweed",
      ],
  },
  "login2": {
      "1h": [
          "cn",
          "cs",
          "de",
          "el",
          "elections",
          "elections-test",
          "en",
          "en-test",
          "es",
          "events",
          "events-test",
          "files",
          "fr",
          "hackweek",
          "hu",
          "it",
          "ja",
          "jitsi",
          "languages",
          "new-forums",
          "nl",
          "nntp",
          "old-de",
          "old-en",
          "pl",
          "pt",
          "ru",
          "sv",
          "tr",
          "tsp",
          "tsp-test",
          "zh",
          "zh-tw",
      ],
  },
  "opensuse.github.io.": {
      "1h": [
          "kernel",
          "osrt",
      ],
  },
  "pontifex": {
      "1h": [
          "drpmsync",
          "ftp",
          "repos",
          "source",
      ],
  },
  "proxy-prg2": {
      "1h": [
          "*.quiz",
          "101",
          "beans",
          "calendar",
          "chat",
          "ci",
          "code-dev",
          "community",
          "connect",
          "contribute",
          "countdown",
          "counter",
          "dimension",
          "doc",
          "etherpad",
          "factory-dashboard",
          "fate",
          "features",
          "fontinfo",
          "gcc",
          "get",
          "hellocf",
          "html5test",
          "idea",
          "ideas",
          "ip",
          "ipfs",
          "kubic",
          "kudos",
          "lizards",
          "lnt",
          "manpages",
          "matrix",
          "metrics",
          "mirrors",
          "monitor",
          "moodle",
          "news",
          "news-test",
          "obs-reviewlab",
          "oom",
          "opi-proxy",
          "osc-collab",
          "osc-collab-test",
          "paste",
          "paste-test",
          "people",
          "planet",
          "pmya",
          "progress",
          "proxy",
          "rpmlint",
          "quiz",
          "search",
          "search-test",
          "security",
          "shop",
          "static",
          "studioexpress",
          "survey",
          "svn",
          "universe",
          "users",
          "webhook",
          "www",
          "www-test",
          "yast",
      ],
      "1d": [
          "redirector",
          "redirector-prg2",
      ],
  },
  "proxy-slc1": {
      "1h": [
          "debuginfod",
          "slc-downloadcontent",
          "slc-mirror",
          "mirrorcache-us",
      ],
      "1d": [
          "redirector-slc1",
      ],
  },
  "redirector": {
      "1h": [
          "apparmor",
          "bar",
          "board",
          "bugs",
          "coc",
          "conference",
          "dewiki",
          "education",
          "fi",
          "git",
          "help",
          "ignite",
          "ignite-stage",
          "is",
          "license",
          "man",
          "party",
          "summit",
          "tube",
          "upgrade",
          "vi",
          "wiki",
      ],
  },
  // TODO: move these into redirector above
  //       no need for redirections to be bound to a site
  "redirector-prg2": {
      "1h": [
          "activedoc",
          "docs",
          "rtfm",
          "www.activedoc",
      ],
  },
  "redirector-slc1": {
      "1h": [
          "provo-downloadcontent",
          "provo-mirror",
      ],
  },
  "obs-login": {
      "30m": [
          "api",
          "api-test",
          "build",
          "build-test",
          "obs-analyze",
          "obs-debug",
          "obs-grafana",
          "obs-login-ucs",
          "obs-measure",
          "obs-telegraf",
          "packages",
          "software",
          "software-stage",
      ],
      "1h": [
          "amqp",
          "br",
          "buildresults",
          "errbit",
          "glitchtip",
          "gs-stats",
          "gs-stats-stage",
          "rabbit",
          "registry",
      ],
  },
  "po1-login": {
      "1h": [
          "po1-amqp",
          "po1-api",
          "po1-auth",
          "po1-build",
          "po1-errbit",
          "po1-rabbit",
          "po1-redis",
          "po1-registry",
      ],
  },
  "stage": {
      "10m": [
          "rsync-repositories",
          "stage-repositories",
      ],
  },
});
